name: CI/CD Pipeline for Portfolio App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  provision-infrastructure:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure

  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: provision-infrastructure
    # THE ONLY OUTPUT WE NEED is the registry, which is a reliable output from the login action.
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: penta-portfolio-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker build -t $IMAGE_URI ./app
          docker push $IMAGE_URI

  deploy-to-eks:
    name: Deploy to EKS with Helm
    runs-on: ubuntu-latest
    needs: build-and-push-image
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-south-1
      - name: Set up Kubeconfig for EKS
        run: aws eks update-kubeconfig --name penta-ai-test --region ap-south-1
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Deploy application with Helm
        run: |
          # Reconstruct the URI using reliable, known values
          ECR_REGISTRY="${{ needs.build-and-push-image.outputs.registry }}"
          ECR_REPOSITORY="penta-portfolio-app"
          IMAGE_TAG="${{ github.sha }}"

          echo "Deploying with Registry: $ECR_REGISTRY"
          echo "Deploying with Repository: $ECR_REPOSITORY"
          echo "Deploying with Tag: $IMAGE_TAG"

          # Fail-fast check
          if [ -z "$ECR_REGISTRY" ]; then
            echo "Error: ECR Registry from build job is empty."
            exit 1
          fi
          
          helm upgrade --install penta-portfolio ./helm/penta-portfolio \
            --set image.repository=$ECR_REGISTRY/$ECR_REPOSITORY \
            --set image.tag=$IMAGE_TAG \
            --namespace default \
            --wait --debug
