name: CI/CD Pipeline for Portfolio App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  provision-infrastructure:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure

  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: provision-infrastructure
    outputs:
      image_uri: ${{ steps.build-image.outputs.image_uri }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: penta-portfolio-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker build -t $IMAGE_URI ./app
          docker push $IMAGE_URI
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

  deploy-to-eks:
    name: Deploy to EKS with Helm
    runs-on: ubuntu-latest
    needs: build-and-push-image
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-south-1
      - name: Set up Kubeconfig for EKS
        run: aws eks update-kubeconfig --name penta-ai-test --region ap-south-1
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Deploy application with Helm
        run: |
          IMAGE_REPO=$(echo "${{ needs.build-and-push-image.outputs.image_uri }}" | cut -d: -f1)
          IMAGE_TAG=$(echo "${{ needs.build-and-push-image.outputs.image_uri }}" | cut -d: -f2)
          
          helm upgrade --install penta-portfolio ./helm/penta-portfolio \
            --set image.repository=$IMAGE_REPO \
            --set image.tag=$IMAGE_TAG \
            --namespace default \
            --wait
